apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: azure-dev-env-dev
  namespace: flux-system
spec:
  interval: 5m
  path: ./charts/azure-dev-env
  prune: true
  sourceRef:
    kind: GitRepository
    name: azure-vm-upbound
  targetNamespace: crossplane-system
  timeout: 2m
  wait: true
  values:
    env: dev
    location: centralus
    vmSize: Standard_D2s_v5
    adminPasswordSecretName: vm-password
